export const meta = {
  name: 'duskspire-v2-build',
  description: 'Duskspire v2: one group of 5 parallel builders (Haiku high; Sonnet medium for design only)',
  phases: [{ title: 'V2 build' }],
}

const ROOT = '<project>'
const HAIKU = { model: 'haiku', effort: 'high' }
const SONNET = { model: 'sonnet', effort: 'medium' }

const PRE = `You are one of 20 engineers working in parallel on version 2 of DUSKSPIRE, a working Slay-the-Spire-style roguelike deckbuilder (plain JS classic scripts on globalThis.DS, no build step, Electron shell).
Project root (Windows): ${ROOT}
FIRST: Read ${ROOT}\\CONTRACT.md completely, especially section 10 (version 2), which defines what is new. It is law: names, signatures, id prefixes, data shapes. Then read the existing source files your task touches or depends on so that you code against what really exists.
Rules:
- Only create/modify the files listed under YOUR FILES (absolute paths). Other engineers are editing the other files right now; code against the contract for anything of theirs that does not exist yet, and guard optional things (e.g. \`DS.art && ...\`, \`DS.Meta && ...\`, \`typeof c.preview === 'function'\`).
- Existing behaviour must keep working. Read before you edit; make surgical edits to large existing files instead of rewriting them.
- Classic-script IIFE style exactly like the existing files. No ES modules, no libraries, no network assets.
- For big new files, write in several steps (Write, then extend with Edit).
- Verify: run \`node --check <file>\` on every JS file you touch (run node from the project root). You may run \`node tools/smoke.js --quick\` to test, but errors it reports in files you do not own are other engineers' work in progress — ignore them.
- A previous attempt at your task may have been interrupted: if your new files already exist, read them and complete them.
- Final message: 3-6 lines — what you built, counts, and any contract ambiguity or bug in someone else's file that you noticed (be specific: file, function, problem).

`

const moreCards = (cls, prefix, hint) => ({
  o: HAIKU, label: `cards2:${cls}`,
  prompt: PRE + `YOUR FILES: src/content/cards_${cls}_2.js (new)
YOUR TASK: an expansion set for the existing '${cls}' character. First read src/content/cards_${cls}.js fully (its cards, custom statuses, archetypes, id list) and skim src/engine/combat.js + statuses.js to know exactly which ops, Value sources, 'when' keys and statuses are implemented.
Add AT LEAST 40 new cards (class '${cls}', ids prefixed ${prefix}, no id or name collisions with the existing file): about 14 common, 17 uncommon, 9 rare, plus any tokens. Goals: ${hint} Every card needs an emoji icon, exact player-facing desc with literal numbers matching the effects, and an upgrade override. Define new custom statuses (prefix ${prefix}, ids must differ from every card id) for new powers — at least 6. You may reference statuses and token cards defined in the existing file (it loads before yours). Also add 3 class relics for '${cls}' (DS.defineRelic, ids ${prefix}relic2_*, one each of rarity common, uncommon, rare) that reward the new archetype. Use only contract-valid DSL; 'custom' at most 2 times.`,
})

const newClass = (cls, prefix, theme) => ({
  o: HAIKU, label: `class:${cls}`,
  prompt: PRE + `YOUR FILES: src/content/cards_${cls}.js (new)
YOUR TASK: a brand-new fifth/sixth playable character '${cls}' (id prefix ${prefix}). Read src/content/cards_berserker.js as the model for structure and quality, and skim src/engine/combat.js + statuses.js to know exactly which ops, Value sources, 'when' keys and statuses are implemented.
Character: ${theme}
Deliver: DS.defineCharacter (id '${cls}', name, title, desc, hp, gold 99, icon, color, starterDeck of 11 ids = 5 Strike + 4 Defend + 2 signature starters, starterRelic), its starter relic (rarity 'starter', class '${cls}'), 4 more class relics (1 common, 1 uncommon, 1 rare, 1 boss; class '${cls}'), at least 14 custom statuses with triggers, and AT LEAST 75 non-starter cards (about 26 common, 32 uncommon, 17 rare; ~40% attack / 40% skill / 20% power) plus token cards (rarity 'special') as needed. 3-4 distinct, interlocking archetypes; include X-cost cards, exhaust/ethereal/innate/retain, multi-hit, Value-object scaling, 'if' conditionals. Every card: emoji icon, exact desc with literal numbers, upgrade override. Balance per the contract reference. Status ids must never equal a card id. 'custom' op at most 3 times.`,
})

const moreEnemies = (n, theme) => ({
  o: HAIKU, label: `enemies2:act${n}`,
  prompt: PRE + `YOUR FILES: src/content/enemies_act${n}_b.js (new)
YOUR TASK: a second bestiary wave for ACT ${n}. First read src/content/enemies_act${n}.js fully (ids, stats, style, custom statuses) and skim src/engine/combat.js for how moves, patterns, ai(ctx), summon, onSpawn and triggers really behave.
Add (ids prefixed a${n}_, no collisions with the existing file; act: ${n}): at least 10 new 'normal' enemies, 2 'minion', 3 'elite', 2 'boss', each with 3-5 moves and a distinctive pattern/ai; and at least 4 'easy', 12 'normal', 4 'elite', 2 'boss' new encounters — mixing new enemies with existing ones from enemies_act${n}.js is encouraged. New theme accents: ${theme}. Favor mechanics the act does not have yet: enemies that punish playing many cards, that steal gold, that grow when you block, that heal allies, that curse your deck (add_card curse_* / status_* to draw or discard), timers, enrage at low HP, shield-bearers protecting a caster, mirror enemies copying your strength, etc. Numbers must match the existing act's power level (compare against its enemies of the same tier) — bosses must be beatable but tense. Define custom statuses with prefix a${n}_ (ids different from all enemy/encounter ids). 'custom' at most 3 times.`,
})

const BUILD = [
  // ---- group 0
  { g: 0, o: HAIKU, label: 'engine:v2', prompt: PRE + `YOUR FILES: src/engine/core.js, src/engine/statuses.js, src/engine/combat.js
YOUR TASK: implement contract 10.2 (DS.settings in core.js) and 10.3 (c.preview, c.log + 'combat:log', difficulty multipliers) and harden the engine:
- c.preview must reuse the same damage/block math as real resolution (factor shared helpers so they cannot drift), resolve Value objects, and never mutate state or emit events.
- Combat log: readable short lines ("You play Cleave.", "Grave Slime takes 8 damage (3 blocked).", "Grave Slime uses Lick: Weak 2.", "Rat dies."), using status names not ids.
- Mark things seen for the meta layer when available: DS.Meta && DS.Meta.markSeen('enemies', id) at spawn, 'cards' when a card is played, 'potions' when used.
- Fix the known problem: a fight abandoned from the menu can keep resolving its enemy turn in the background — make every await point in turn/effect resolution bail out once the combat is ended/abandoned.
- Audit pass: read combat.js top to bottom looking for real bugs (trigger ordering, death during multi-hit, effects continuing after combat end, statuses applied to dead units, hand-limit overflow going to discard, X-cost with cost modifiers, retain/ethereal interplay, block decay with barricade, intent recomputation, random target when no enemies alive, negative strength math, 'every' counters, oncePerTurn resets). Fix what you find and list each fix.
- tools/engine_selftest.js must still pass (\`node tools/engine_selftest.js\`); \`node tools/smoke.js --quick\` must not get worse in engine-attributable errors.` },
  { g: 0, ...newClass('tempest', 'tp_', 'The Tempest — a wandering storm-monk (72 HP, color #8e44ad, icon 🌩️). Archetypes: "Momentum" (custom status gained per card played this turn, spent by finishers; rewards long combo turns with cheap cards and draw); "Stances" implemented as mutually exclusive custom statuses — Gale (attacks hit harder, take more damage) and Stillness (gain block at turn end, generate energy when leaving) with cards that enter/leave them; "Static" (stacking charge on enemies that detonates for damage when it reaches a threshold or when a trigger card is played, using Value objects and multiply_status); retain-heavy "storing the storm" cards that grow while held. Starter relic: the first card played each turn that costs 2 or more gives 1 energy back... if that is not expressible, use: at the start of each combat gain 1 Momentum-related buff.') },
  { g: 0, ...moreCards('berserker', 'bz_', 'deepen the existing archetypes and add one new archetype, "Warcry": skills that buff the next attack (vigor, double_tap), wound-yourself status cards as fuel (add status_wound to hand/discard then cards that exhaust or count them), and block-from-aggression tools so the class has a real defensive line.') },
  { g: 0, ...moreEnemies(1, 'grave-robbers, ember sprites, bone hounds, a mimic chest, fungus shamans, a cursed bell') },
  { g: 0, o: SONNET, label: 'design:styles', prompt: PRE + `YOUR FILES: styles.css
YOU ARE THE VISUAL DESIGNER. Read styles.css fully, then src/ui/kit.js, src/ui/screens.js and src/ui/combat_ui.js to see every class in use and how the DOM is structured.
YOUR TASK: take the look from "decent dark theme" to a polished, cohesive, premium dark-fantasy card game, and add rules for every new class in contract 10.5.
- Establish a real design system at the top of the file: CSS custom properties for palette (deep indigo/black base, ember-gold accent, per-rarity and per-type colors), type scale, spacing, radii, shadows, glows, z-index layers, motion timings; then refactor existing rules to use them.
- Cards are the star: layered frame with class-color tint (--class-color), rarity gems/trim (common steel, uncommon azure, rare gold, special violet, curse sickly), type banners, cost orb with depth, legible description at both sizes, upgraded-name glow, satisfying hover/selected/disabled/dragging states, playable-glow.
- Combat: the entire hand must be visible at 1280x720 (cards may overlap/fan and scale with viewport height via clamp()/vh; hovered card lifts fully into view above its neighbours), clear zones for player / enemies / piles / energy / end turn, intent badges, hp bars with block overlay and damage-chip animation, status chips, elite/boss treatments (.ds-tier-elite, .ds-tier-boss), targeting states, .ds-target-arrow, .ds-preview-badge, .ds-combat-log panel (right side, collapsible, unobtrusive).
- Map: parchment-or-starfield feel, distinct node types, pulsing available nodes, visited path highlighting, readable legend.
- Screens: menu title treatment (large engraved DUSKSPIRE logotype with glow/animated embers using only CSS), character select cards, reward/shop/event/rest/treasure layouts, history/stats/achievements, settings rows, sliders and toggles, how-to-play, compendium tabs and search, toast/modal/tooltip polish, scrollbars.
- Responsive from 1280x720 to 2560x1440 without horizontal scroll; respect prefers-reduced-motion.
- Do not rename or remove existing class names (the JS depends on them). Keep the file valid CSS with balanced braces; verify by loading http://localhost:8123 is NOT available to you necessarily — instead sanity-check with a quick node script that counts braces, and re-read your diff.
Final message: summarize the design system and list any class used in JS that you found without a rule and added.` },
  // ---- group 1
  { g: 1, o: HAIKU, label: 'run:v2', prompt: PRE + `YOUR FILES: src/engine/run.js
YOUR TASK: implement contract 10.4 completely.
- Ascension: DS.Run.ASCENSIONS with 10 cumulative, clearly described levels (e.g. 1 elites +15% HP; 2 normal enemies +10% damage; 3 heal 25% at rest instead of 30%; 4 start with a random curse; 5 bosses +20% HP; 6 less gold from fights; 7 shop prices +10%; 8 enemies +10% HP; 9 start each act with -10% current HP ... 10 enemies +10% damage and one fewer potion slot) and compute run.difficulty from run.ascension in start(). Apply the run-side ones here (rest heal, gold, prices, start curses); combat.js applies the enemy multipliers from run.difficulty.
- DS.Run.start(characterId, opts) with {seed, ascension}; bare number seed still works. Record run.lastEncounterId when a combat room is entered.
- DS.Run.score(run): floors climbed, elites/bosses killed, gold, win bonus, ascension multiplier.
- DS.Meta exactly as specified (persistent, guarded for Node, tolerant of corrupt/missing storage), with at least 30 achievements spanning: first win per character (6 characters: berserker, shade, arcanist, warden, tempest, occultist), ascension milestones, deck-size extremes, no-damage boss kill is hard so prefer things measurable from run state at run end or via DS.Meta.unlock calls from here (e.g. hold 500 gold, 15 relics, win with a 40+ card deck, win with <= 15 cards, 5 curses in deck, reach act 3, lose on floor 1, win in under N turns). DS.Run.end records the run and evaluates achievements. Mark relics/cards seen when added to the run.
- Resume correctness: leaving inside any room (event, shop, rest, treasure, reward screen after a fight, boss relic choice) and Continue must return to that room with the same contents and without double-granting or skipping rewards. Extend the existing pending/snapshot mechanism: persist the current room object (run.room = {type, ...payload, stage}) and expose DS.Run.resumeTarget() -> {screen, params} | null for the UI to route to on Continue. Document the exact shapes in a comment block at the top of run.js so the UI engineer can match them.
- Add support for {op:'fight', encounter:'random_normal'|'random_elite'} in run-level effects (pick from the current act).
- More variety: 2 extra map layouts chosen by seed (denser / sparser paths), and "treasure" rooms may contain a small random bonus.
- Keep everything already working; \`node tools/smoke.js --quick\` must not get worse in run.js-attributable errors.` },
  { g: 1, ...newClass('occultist', 'oc_', 'The Occultist — a forbidden-lore witch (66 HP, color #16a085, icon 🕯️). Archetypes: "Hex" (stacking custom debuff on enemies: when a hexed enemy attacks it loses HP per stack / takes bonus damage, with cards that spread, double via multiply_status, or consume Hex); "Sacrifice" (cards that add curses/status cards to your own deck or exhaust your own cards for big payoffs, and powers that reward drawing or exhausting curses/status cards via onCardDrawn/onCardExhausted triggers); "Lifedrain" (damage that heals, max-HP manipulation, regen, effects keyed to missing_hp); "Ritual" (slow powers and retain cards that scale every turn — ritual, metallicize, growing strength). Starter relic: whenever you exhaust a card, gain 2 block.') },
  { g: 1, ...moreCards('shade', 'sh_', 'deepen poison/shiv/discard and add one new archetype, "Ambush": innate and retain setup cards, big payoffs on turn 1-2 (when:{turn:1}-style statuses, Value source turn), marks (the built-in mark status as a combo counter consumed by finishers), and intangible/evasion at a price.') },
  { g: 1, ...moreEnemies(2, 'drowned sailors, tide witches, brass automatons with wind-up timers, tax collectors that steal gold, coral golems, a kraken tentacle swarm') },
  { g: 1, o: SONNET, label: 'design:art', prompt: PRE + `YOUR FILES: src/ui/art.js (new), src/ui/kit.js
YOU ARE THE ILLUSTRATOR / ART DIRECTOR. The game currently uses bare emoji as art. Build DS.art exactly per contract 10.5 — procedural, deterministic (seeded by id hash, never Math.random at render), inline SVG, no external assets — and integrate it into kit.js.
- cardArt(data): a small illustrated scene per card: layered SVG background generated from the card's id hash (shapes, rays, runes, mist, embers, lightning, vines — motif chosen by class and type: attacks get slashes/impact rays, skills get shields/sigils/circles, powers get radiant mandalas/auras, curses get cracked/thorned dark motifs, status get dull static), tinted by the class color (DS.characters[data.class].color; sensible fixed palettes for colorless/curse/status), rarity influencing richness, with the card's emoji rendered large and crisp as the centrepiece with a soft shadow/glow. Must look good at 150x90 and at half that.
- unitArt(def, {size}): enemy/character portraits: emoji centrepiece over a procedural aura + ground shadow + silhouette backdrop keyed by tier (normal subtle, elite spiked crimson halo, boss large ornate animated aura) and act palette (act 1 ash/ember, act 2 teal/brass, act 3 violet/starlight); characters use their color. Gentle idle animation via SVG/CSS (breathing bob), disabled under prefers-reduced-motion.
- applyBackdrop(rootEl, name, act): atmospheric full-screen layered backgrounds built from gradients + inline SVG (data URI or appended absolutely-positioned element with class ds-backdrop, pointer-events none, behind content): catacomb arches and embers (act 1), drowned skyline with light shafts and bubbles (act 2), jagged summit with aurora and stars (act 3); distinct moods for menu (the spire silhouette against a dusk sky), map, shop (warm lantern), rest (campfire glow), event, treasure, victory (dawn), gameover (blood moon). Subtle parallax/drift animation, cheap to render.
- relicIcon(def) / potionIcon(def): emoji in a procedural medallion (rarity-colored ring) / in a flask shape filled with def.color.
- art.js injects its own small <style> for its animations. Everything must be defensive: unknown ids, missing fields, null input → still returns a valid element.
- kit.js integration (surgical edits; read it fully first): renderCard uses DS.art.cardArt inside .ds-card-art when DS.art exists (fallback to emoji); export DS.ui.unitArt(def, opts) / DS.ui.relicIcon / DS.ui.potionIcon thin wrappers that fall back to emoji spans so other UI files can call them unconditionally; the screen router calls DS.art.applyBackdrop(rootEl, name, DS.run && DS.run.act) on every screen enter. Do not change any existing kit function signature.
- Performance: a hand of 10 cards and a compendium grid of 400+ cards must stay smooth — cache generated SVG markup by id+upgraded, keep node counts per card modest (< 40 elements), and lazy-render compendium art with IntersectionObserver if needed.
Verify with node --check and a quick Node harness using a minimal fake document if practical; re-read your code for SVG validity.` },
  // ---- group 2
  { g: 2, o: HAIKU, label: 'combat-ui:v2', prompt: PRE + `YOUR FILES: src/ui/combat_ui.js
YOUR TASK: implement the combat_ui part of contract 10.5 with surgical edits to the existing file (read it fully first; also read kit.js, fx.js, styles.css combat rules and combat.js).
- Live numbers: for each hand card show a .ds-preview-badge with c.preview(card, hoveredOrOnlyEnemy) damage (e.g. "9" or "6×3") and/or block when they differ from nothing (guard typeof c.preview); when hovering an enemy with a card selected show the exact damage and whether it kills. Enemy intent already shows modified damage — keep.
- Add ds-tier-<tier> class to enemy elements; use DS.ui.unitArt(def, {size}) for enemy and player portraits when it exists (fallback: current emoji), and DS.ui.potionIcon similarly in the potion modal.
- Drag-to-play: press on a playable card and drag; for 'enemy'-target cards draw an SVG .ds-target-arrow from the card to the pointer and highlight the enemy under it, release on an enemy to play; non-targeted cards play when released above the hand zone; releasing elsewhere cancels. Click-to-play and keyboard controls must keep working exactly as before. Add .ds-card-dragging while dragging.
- Combat log: collapsible .ds-combat-log panel listing 'combat:log' entries (.ds-log-entry), auto-scrolling, toggled by a button and the L key, initial state from DS.settings.get('showLog', true) when DS.settings exists.
- End turn: if DS.settings.get('confirmEndTurn') and the player still has energy and a playable card, ask via DS.ui.modal first. Space also ends the turn.
- Whole hand visible at 1280x720: remove any inline sizing that fights styles.css; the designer is making .ds-hand responsive — do not hard-code pixel heights for cards.
- Quality: hovering a card shows a tooltip explaining every keyword/status mentioned in its description (names + descs from DS.statuses, plus Exhaust/Ethereal/Innate/Retain/Block explanations); clicking the player or an enemy opens a detail modal listing its statuses with full descriptions and, for enemies, its move list names; show "x2" style badge when double_tap is active is optional.
- No memory leaks: every listener added in enter() is removed in exit(), including document-level drag listeners.` },
  { g: 2, o: HAIKU, label: 'screens:v2', prompt: PRE + `YOUR FILES: src/ui/screens.js, src/ui/boot.js
YOUR TASK: implement the screens part of contract 10.5 with surgical edits (read screens.js, boot.js, kit.js and run.js fully first).
- New screens registered with DS.ui.registerScreen: 'history' (lifetime stat tiles .ds-stat-tile: runs, wins, win rate, best score, per-character wins and highest ascension; run history list .ds-history-row(-won/-lost) with character icon, result, act/floor, ascension, score, killed-by, date; achievements grid .ds-achievement(-locked) from DS.Meta.ACHIEVEMENTS; a guarded "Reset progress" button), 'settings' (.ds-settings-row: game speed 1x/2x/3x, volume .ds-slider, mute and music .ds-toggle, confirm end turn, screen shake, show combat log, fullscreen via document.documentElement.requestFullscreen guarded; all through DS.settings and applied live — audio via DS.audio.setMuted/setVolume/setMusic when present), 'howto' (.ds-howto: clear how-to-play in sections — goal, turn structure, energy/cards, block, intents, map rooms, relics/potions, upgrading, ascension — plus an auto-generated keyword glossary from built-in DS.statuses).
- Menu: buttons for Continue / New Run / Compendium / History / Settings / How to Play / Quit (window.close, only shown when running in Electron: navigator.userAgent includes 'Electron'). Show version "v2" and total wins.
- charselect: lists all DS.characters (now up to 6 — layout must handle 6 gracefully: grid or horizontal scroll), ascension picker (.ds-asc-picker with .ds-asc-pip buttons 0..DS.Meta.maxAscension(char), locked pips above that, tooltip describing each level from DS.Run.ASCENSIONS), optional seed input; starts via DS.Run.start(id, {seed, ascension}). Show a short "how this class plays" line and 3 sample cards from its pool (hover preview).
- Continue: use DS.Run.resumeTarget() when it exists to route to the exact room/screen the player left (else map). Make reward / shop / event / rest / treasure / bossrelic screens read their state from the persisted room object (run.room) when present so a resumed room does not regenerate or double-grant; follow the shape documented at the top of run.js if it exists by the time you read it, otherwise code defensively to contract 10.4 and note the assumption in your final message.
- Compendium: .ds-search-input filtering by name/description text, .ds-tab tabs, filters by class/type/rarity/cost, sort options, undiscovered entries dimmed with .ds-undiscovered when DS.Meta exists (still visible), counts "seen / total"; enemies tab shows moves on click; add a Statuses/Keywords tab. Must stay fast with 600+ cards (render in chunks / on scroll).
- Game over and victory screens: show score (DS.Run.score), ascension, killed-by, newly unlocked achievements, "next ascension unlocked" message, deck and relic recap, buttons: New Run (same character), Menu.
- Reward screen: card choices show full-size cards with hover tooltips, a "Skip" that is explicit, and (when DS.run has it) a "Deck" button to review the deck before choosing. Shop: tooltips on relics/potions, sale tag on one random card (visual only if run.js gives a sale flag), clear "leave" button.
- Top bar: ascension badge when > 0, use DS.ui.relicIcon/potionIcon when they exist, show seed in settings/abandon modal.
- boot.js: DS.hooks.delay honours DS.settings speed (ms / speed); listen for 'meta:achievement' and toast "Achievement unlocked: <name>"; apply persisted settings (mute/volume/music) on boot.
- Use the new CSS class names from contract 10.5 (styles.css is being redesigned by the designer; do not write CSS, do not inject style tags).` },
  { g: 2, ...moreCards('arcanist', 'ar_', 'deepen Arcane Charge / Burn / Frost and add one new archetype, "Lightning": random_enemy multi-hits that scale with cards_played, chain effects (damage all then bonus to a random enemy), lock_on setups, and 0-cost "spark" tokens; also give the class 4-5 solid defensive commons.') },
  { g: 2, ...moreEnemies(3, 'star-eaten pilgrims, mirror wraiths that copy your strength, hourglass sentinels on a timer, void leeches that grow when you block, a choir of fallen seraphs that heal each other, living constellations') },
  { g: 2, o: SONNET, label: 'design:juice', prompt: PRE + `YOUR FILES: src/ui/fx.js, src/ui/audio.js
YOU ARE THE MOTION + SOUND DESIGNER. Read both files fully, plus combat_ui.js, kit.js and the event list in CONTRACT.md section 7, and section 10.
YOUR TASK: make the game FEEL great — surgical upgrades, everything self-wired through DS.events, nothing may throw when DOM elements are missing, respect DS.settings ('screenShake', 'volume', 'muted', 'music' — guard DS.settings existence) and prefers-reduced-motion.
- fx.js: (1) impact feel: hit-stop-style punch (brief scale/flash on the target [data-combatant]), directional slash / blunt / magic-burst / poison-drip / fire / frost variants chosen from the card's type, class and description keywords; damage numbers that pop, arc and fade with size and color scaled by amount (crit-style treatment for hits >= 20), stacked numbers offset so multi-hits read clearly; block shield ripple; heal sparkles; status application icon pop near the unit; enemy death dissolve with shards; player hit vignette flash; screen shake scaled by damage. (2) card feel: on 'combat:cardPlayed' a ghost of the card flies from the hand toward the target and dissolves; 'combat:cardDrawn' subtle shimmer at the draw pile; 'combat:shuffle' card-riffle arc from discard to draw pile; exhaust burns away with embers. (3) turn banners are owned by combat_ui — do not add your own. (4) reward moments: gold coin fountain to the top bar on 'run:gold', relic pickup radiant burst on 'run:relic', card added flourish on 'run:card', achievement confetti on 'meta:achievement', victory fireworks when the victory screen is entered (observe DS.ui.current or a MutationObserver on #app), ambient drifting embers/dust particles on a single pooled canvas or a capped DOM pool behind the UI. Use a particle pool with a hard cap (<= 150 live particles) and requestAnimationFrame only while particles are alive.
- audio.js: richer synthesized sound design with WebAudio (layered oscillators + filtered noise + short convolution-free reverb via feedback delay): weighty hits scaled by damage, distinct timbres per card type and per damage flavor (slash, blunt, fire, poison, frost, lightning inferred from card/status ids), satisfying block clang, buff shimmer, debuff sag, coin clinks, card flick/draw/shuffle, enemy death thud, UI hover tick and click, relic chime, achievement fanfare, boss-intro sting. Adaptive music: distinct generative loops (tempo, scale, instrumentation) for menu, map (per act 1/2/3), normal combat, elite combat, boss combat, shop/rest calm, victory and defeat stingers, with smooth 1-2s crossfades driven by screen changes and 'combat:start' encounter tier. Master gain, per-bus gains (sfx/music), DS.audio.setVolume(0..1), setMuted, setMusic, limiter (DynamicsCompressor) to avoid clipping, voice cap to avoid overload, lazy AudioContext on first gesture, suspend when the page is hidden.
Keep the public API of both files compatible with what exists. node --check both; re-read for runtime errors.` },
  // ---- group 3
  { g: 3, o: HAIKU, label: 'tooling:v2', prompt: PRE + `YOUR FILES: index.html, tools/smoke.js, tools/tests.js (new), tools/balance.js (new), package.json
YOUR TASK:
1. index.html: add the new script tags per contract 10.1 (exact order). Missing files must not break the page beyond a console 404.
2. tools/smoke.js: update for v2 — load the new content files; new id prefixes and the "reuse prefix" rule for *_2.js and *_b.js files; six characters (tempest, occultist included when their files exist); starter decks of 11; new op value 'random_normal'/'random_elite' for run-level fight; validate DS.settings, c.preview (pure: state deep-equal before/after, sane numbers for every card vs a dummy enemy), c.log growth, difficulty multipliers (ascension 10 run: enemies spawn with more HP), DS.Meta round trip with a fake localStorage, DS.Run.ASCENSIONS shape, resume: for each room type enter the room, save, load, and check DS.Run.resumeTarget() points back to it. New checks must report as errors only when the feature exists but is wrong; when a v2 API is entirely missing report one clear "v2 API missing: X" error per API (other engineers are implementing them right now). Keep all existing checks and the report format, including the final "SMOKE RESULT:" line and --quick/--only flags.
3. tools/tests.js: a real unit-test suite for the engine, runnable with \`node tools/tests.js\`, loading core/statuses/combat/run plus content the same way smoke.js does, with a tiny assert/test harness (no deps) and AT LEAST 150 focused test cases with clear names: every combat op, every Value source, every built-in status's exact behaviour and decay timing (weak 25%, vulnerable 50%, frail, poison tick then decrement, burn, regen, thorns, plated_armor loss on attack damage, metallicize, artifact negation, intangible, barricade, ritual, energized, draw_next, next_turn_block, strength_down, no_draw, entangle, buffer, rage, double_tap, vigor, curl_up, enrage, angry), trigger semantics (when keys, every, oncePerTurn, oncePerCombat), card keywords (exhaust, ethereal, innate, retain, X cost, unplayable, playableIf), piles and shuffling, hand limit, enemy patterns (sequence, random weights/noRepeat/first, ai), summon cap, death handling mid multi-hit, onKill, combat end conditions, potions, relic passives, and run-level logic (map invariants over 200 seeds: connectivity, row types, no orphan nodes; rewards rarity; shop pricing; rest; each run-level op; event conds; save/load equality; nextAct). Use deterministic seeds and purpose-built test cards/enemies defined inside the test file (prefix t_). Print per-test pass/fail, a summary, and exit 1 on failure. Run it; for every failing test decide whether the test or the engine is wrong per the contract — fix wrong tests; leave genuine engine failures failing and list each one precisely in your final message (the engine owners are busy in those files — do not edit them).
4. tools/balance.js: a balance simulator runnable with \`node tools/balance.js [--runs=N] [--char=id] [--asc=N]\`: a competent heuristic bot (lethal check first; prioritise block when incoming intent damage exceeds block and no lethal; play powers early; spend energy efficiently by value-per-energy estimated from c.preview / effect inspection; focus the lowest-HP or most dangerous enemy; use potions in elite/boss fights or when below 40% HP; picks card rewards by rarity + simple synergy score, skips when deck > 30; rests when below 60% HP else upgrades; buys relics then removes Strikes at shops; takes safe event options) playing complete 3-act runs. Default 30 runs per character. Report per character: win rate, average floor reached, death distribution by encounter (top killers), average HP lost per encounter id (top 15 most damaging per act), per-act survival rate, most/least picked cards and relics and their win correlation, average turns per fight by tier. Must tolerate missing v2 APIs (fallbacks) and never hang (per-fight turn cap and wall-clock cap). Add npm scripts "test" and "balance" to package.json.` },
  { g: 3, ...moreCards('warden', 'wd_', 'deepen block/thorns/regen/growth and add one new archetype, "Bulwark Bash": attacks that spend block for damage, taunt-like marks, retaliate statuses that trigger on onAttacked/onBlockBroken, and a few fast aggressive options so the class is not purely slow.') },
  { g: 3, o: HAIKU, label: 'relics:c', prompt: PRE + `YOUR FILES: src/content/relics_c.js (new)
YOUR TASK: read src/content/relics_a.js and relics_b.js (to avoid duplicates and match style) and skim combat.js + run.js for exactly which triggers, 'when' keys, passives and run-level triggers are really implemented. Then add AT LEAST 60 new relics (ids prefixed rc_): 18 common, 16 uncommon, 12 rare, 6 boss, 4 shop, 4 event — every one mechanically distinct from the existing 106 (no "same effect, different number"). Include build-arounds that create new ways to play: relics keyed to curses/status cards, to deck size, to gold held (Value source gold), to potion use, to exhaust count, to playing exactly N cards a turn (every counters), to turn number, to elite/boss rooms, to low/high HP thresholds, to block broken, to shuffles; 2 relics for each of the six classes (class: berserker, shade, arcanist, warden, tempest, occultist — for tempest and occultist use only built-in statuses since their files are being written right now). Boss relics need real trade-offs. Each: evocative name, emoji icon, exact desc, flavor line. Custom statuses prefixed rc_ when needed. 'custom' at most 4 times.` },
  { g: 3, o: HAIKU, label: 'potions+events:c', prompt: PRE + `YOUR FILES: src/content/potions_b.js (new), src/content/events_c.js (new)
YOUR TASK: read src/content/potions.js, events_a.js, events_b.js (avoid duplicates, match style), the encounter ids in src/content/enemies_act1.js / enemies_act2.js / enemies_act3.js, and the run-level interpreter in src/engine/run.js to know exactly which ops and cond keys work.
1. potions_b.js: AT LEAST 25 new potions (ids pb_): 10 common, 9 uncommon, 6 rare — novel effects only (e.g. convert block to damage, duplicate statuses with multiply_status, give an enemy a status that hurts it when it attacks, swap to a defensive stance for a turn, add upgraded random rare card to hand, summon-proofing AoE weak+vulnerable, energy next turn + draw now, exhaust all curses/status in hand and gain block per card via Value sources, etc.). Each with name, emoji icon, color, exact desc.
2. events_c.js: AT LEAST 30 new events (ids ec_): 12 act 'any', 6 each for act [1], [2], [3]. Multi-layered choices with real trade-offs; at least 10 events include a fight choice using {op:'fight', encounter:'<real encounter id from that act>'} (only in act-specific events, using ids that exist in that act's file) or 'random_normal' / 'random_elite' (being added to run.js now), with the reward described in the label granted through effects placed before the fight op; at least 8 use 'chance' gambles with thenResult/elseResult; several are gated by cond (minGold, minHp, hasCardType). Include a few memorable recurring characters (a debt-collecting merchant, a rival climber, a talking skull). Atmospheric second-person narration, exact mechanical labels in brackets, at least one always-available choice per event. No 'custom' ops.` },
  { g: 3, o: HAIKU, label: 'cards:colorless2', prompt: PRE + `YOUR FILES: src/content/cards_colorless_2.js (new)
NOTE: this file is not yet in the load order of index.html / tools/smoke.js. That is expected — the integration engineer adds it after you finish; state this clearly in your final message.
YOUR TASK: read src/content/cards_colorless.js fully and skim combat.js + statuses.js for what is really implemented. Add AT LEAST 40 new colorless cards (class 'colorless', ids prefixed cl_, no id/name collisions): 20 uncommon, 15 rare, 5 special (event/relic-only). Themes the pool lacks: cross-class enablers (cards that reward mixing card types in a turn via attacks_played/cards_played), deck manipulation (draw then discard, exhaust-for-value, retain helpers), tempo cards (0-cost with drawbacks, ethereal bombs), economy cards (gold on kill via onKill, gold-scaling damage with Value source gold), risk cards that add curses/status cards for power, anti-boss tools (percent-of-max-hp via Value source max_hp of target with mul, capped), universal defensive staples. Also 5 new curses (ids curse_*, new names, each with a distinct mechanical drawback) and 3 new status cards (ids status_*). Every non-curse/status card: emoji icon, exact desc, upgrade override. Custom statuses prefixed cl_ (ids different from every card id). 'custom' at most 2 times.` },
]

phase('V2 build')
const mine = BUILD.filter(b => b.g === args.group)
const built = await parallel(mine.map(b => () => agent(b.prompt, { ...b.o, label: b.label, phase: 'V2 build' })))
return mine.map((b, i) => ({ label: b.label, model: b.o.model, summary: built[i] ? String(built[i]).slice(0, 900) : null }))
